# How the data gets concatenated

In [1]:
import pandas as pd

df_01 = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
df_02 = pd.DataFrame({'a': [10, 20, 30], 'b': [40, 50, 60], 'c': [70, 80, 90]})
df_03 = pd.DataFrame({'a': [100, 200, 300], 'b': [400, 500, 600], 'c': [700, 800, 900]})

df_big = pd.DataFrame()

In [2]:
df_big = df_big.append(df_01, ignore_index=True)
df_big

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [3]:
df_big = df_big.append(df_02, ignore_index=True)
df_big

a   b   c
0   1   4   7
1   2   5   8
2   3   6   9
3  10  40  70
4  20  50  80
5  30  60  90

In [4]:
df_big = df_big.append(df_03, ignore_index=True)
df_big

a    b    c
0    1    4    7
1    2    5    8
2    3    6    9
3   10   40   70
4   20   50   80
5   30   60   90
6  100  400  700
7  200  500  800
8  300  600  900

In [6]:
df_big.reset_index(drop=True, inplace=True)
df_big

a    b    c
0    1    4    7
1    2    5    8
2    3    6    9
3   10   40   70
4   20   50   80
5   30   60   90
6  100  400  700
7  200  500  800
8  300  600  900

# pd.numeric

In [12]:
df = pd.DataFrame({'a': [1, 2, 3], 'b': [4, None, 'k'], 'c': [7, 8, None]})
df

a     b    c
0  1     4  7.0
1  2  None  8.0
2  3     k  NaN

In [16]:
df = df.apply(pd.to_numeric, errors = 'coerce')
df

a    b    c
0  1  4.0  7.0
1  2  NaN  8.0
2  3  NaN  NaN

# isna()

In [17]:
df.isna()

a      b      c
0  False  False  False
1  False   True  False
2  False   True   True

In [18]:
df.isna().sum()

a    0
b    2
c    1
dtype: int64

In [19]:
df.isna().sum().sum()

3

# df.interpolate()

In [21]:
df_04 = pd.DataFrame({'a': [1, 2, 3, 4], 'b': [4, None, 6, 6], 'c': [8, None, None, 7], 'd': [None, 9, None, 8]})
df_04

a    b    c    d
0  1  4.0  8.0  NaN
1  2  NaN  NaN  9.0
2  3  6.0  NaN  NaN
3  4  6.0  7.0  8.0

In [22]:
df_04 = df_04.interpolate()
df_04

a    b         c    d
0  1  4.0  8.000000  NaN
1  2  5.0  7.666667  9.0
2  3  6.0  7.333333  8.5
3  4  6.0  7.000000  8.0

# np.expand_dims

In [4]:
import numpy as np
example_np_array = np.array([[1, 2, 3], [4, 5, 6]])
example_np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
np.expand_dims(example_np_array, -1)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [9]:
# same as
np.expand_dims(example_np_array, axis=2)

array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])